# Generated by Django 5.2.16 on 2026-07-18 05:15

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=courses.models.attachment_upload_path),
        ),
    ]
